code --install-extension aaron-bond.better-comments --force
code --install-extension ms-vscode.cpptools --force
code --install-extension ms-vscode.cmake-tools --force
code --install-extension ms-azuretools.vscode-docker --force
code --install-extension codezombiech.gitignore --force
code --install-extension eamodio.gitlens --force
code --install-extension wix.vscode-import-cost --force
code --install-extension ms-toolsai.jupyter --force
code --install-extension shd101wyy.markdown-preview-enhanced --force
code --install-extension monokai.theme-monokai-pro-vscode --force
code --install-extension pnp.polacode --force
code --install-extension ms-python.python --force
code --install-extension ms-ceintl.vscode-language-pack-ru --force
code --install-extension emmanuelbeziat.vscode-great-icons --force
